<?php

namespace App\Http\Controllers;

use App\Models\City;
use App\Models\Country;
use Illuminate\Http\Request;
use App\Traits\{response};
use Validator;

class CountryController extends Controller
{

    use response;

    public function getcountries(){
       $countries=Country::where('status',1)->get();
       $data['countries']=$countries;
       return $this->response(true,'get countries successfuly',$data);
    }

    public function getcities(Request $request){
        $validator =Validator::make($request->all(), [
            'country_id'=>'required'
          ]);
          if ($validator->fails()) {
           return response()->json([
               'message'=>$validator->messages()->first()
           ],403);
           }
        $cities=City::where('status',1)->where('country_id',$request->country_id)->get();
        $data['cities']=$cities;
        return $this->response(true,'get cities successfuly',$data);
    }


    public function storeCountries(){
        $countries_ar =  array(
            1 => array('id' => 275, 'alpha2' => 'ps', 'alpha3' => 'pse', 'name' => 'فلسطين'),
            4 => array('id' => 4, 'alpha2' => 'af', 'alpha3' => 'afg', 'name' => 'أفغانستان'),
            8 => array('id' => 8, 'alpha2' => 'al', 'alpha3' => 'alb', 'name' => 'ألبانيا'),
            12 => array('id' => 12, 'alpha2' => 'dz', 'alpha3' => 'dza', 'name' => 'الجزائر'),
            20 => array('id' => 20, 'alpha2' => 'ad', 'alpha3' => 'and', 'name' => 'أندورا'),
            24 => array('id' => 24, 'alpha2' => 'ao', 'alpha3' => 'ago', 'name' => 'أنغولا'),
            28 => array('id' => 28, 'alpha2' => 'ag', 'alpha3' => 'atg', 'name' => 'أنتيغوا وباربودا'),
            32 => array('id' => 32, 'alpha2' => 'ar', 'alpha3' => 'arg', 'name' => 'الأرجنتين'),
            51 => array('id' => 51, 'alpha2' => 'am', 'alpha3' => 'arm', 'name' => 'أرمينيا'),
            36 => array('id' => 36, 'alpha2' => 'au', 'alpha3' => 'aus', 'name' => 'أستراليا'),
            40 => array('id' => 40, 'alpha2' => 'at', 'alpha3' => 'aut', 'name' => 'النمسا'),
            31 => array('id' => 31, 'alpha2' => 'az', 'alpha3' => 'aze', 'name' => 'أذربيجان'),
            44 => array('id' => 44, 'alpha2' => 'bs', 'alpha3' => 'bhs', 'name' => 'باهاماس'),
            48 => array('id' => 48, 'alpha2' => 'bh', 'alpha3' => 'bhr', 'name' => 'البحرين'),
            50 => array('id' => 50, 'alpha2' => 'bd', 'alpha3' => 'bgd', 'name' => 'بنغلاديش'),
            52 => array('id' => 52, 'alpha2' => 'bb', 'alpha3' => 'brb', 'name' => 'باربادوس'),
            112 => array('id' => 112, 'alpha2' => 'by', 'alpha3' => 'blr', 'name' => 'بيلاروس'),
            56 => array('id' => 56, 'alpha2' => 'be', 'alpha3' => 'bel', 'name' => 'بلجيكا'),
            84 => array('id' => 84, 'alpha2' => 'bz', 'alpha3' => 'blz', 'name' => 'بليز'),
            204 => array('id' => 204, 'alpha2' => 'bj', 'alpha3' => 'ben', 'name' => 'بنين'),
            64 => array('id' => 64, 'alpha2' => 'bt', 'alpha3' => 'btn', 'name' => 'بوتان'),
            68 => array('id' => 68, 'alpha2' => 'bo', 'alpha3' => 'bol', 'name' => 'بوليفيا'),
            70 => array('id' => 70, 'alpha2' => 'ba', 'alpha3' => 'bih', 'name' => 'البوسنة والهرسك'),
            72 => array('id' => 72, 'alpha2' => 'bw', 'alpha3' => 'bwa', 'name' => 'بوتسوانا'),
            76 => array('id' => 76, 'alpha2' => 'br', 'alpha3' => 'bra', 'name' => 'البرازيل'),
            96 => array('id' => 96, 'alpha2' => 'bn', 'alpha3' => 'brn', 'name' => 'بروناي'),
            100 => array('id' => 100, 'alpha2' => 'bg', 'alpha3' => 'bgr', 'name' => 'بلغاريا'),
            854 => array('id' => 854, 'alpha2' => 'bf', 'alpha3' => 'bfa', 'name' => 'بوركينا فاسو'),
            108 => array('id' => 108, 'alpha2' => 'bi', 'alpha3' => 'bdi', 'name' => 'بوروندي'),
            116 => array('id' => 116, 'alpha2' => 'kh', 'alpha3' => 'khm', 'name' => 'كمبوديا'),
            120 => array('id' => 120, 'alpha2' => 'cm', 'alpha3' => 'cmr', 'name' => 'الكاميرون'),
            124 => array('id' => 124, 'alpha2' => 'ca', 'alpha3' => 'can', 'name' => 'كندا'),
            132 => array('id' => 132, 'alpha2' => 'cv', 'alpha3' => 'cpv', 'name' => 'الرأس الأخضر'),
            140 => array('id' => 140, 'alpha2' => 'cf', 'alpha3' => 'caf', 'name' => 'جمهورية أفريقيا الوسطى'),
            148 => array('id' => 148, 'alpha2' => 'td', 'alpha3' => 'tcd', 'name' => 'تشاد'),
            152 => array('id' => 152, 'alpha2' => 'cl', 'alpha3' => 'chl', 'name' => 'تشيلي'),
            156 => array('id' => 156, 'alpha2' => 'cn', 'alpha3' => 'chn', 'name' => 'الصين'),
            170 => array('id' => 170, 'alpha2' => 'co', 'alpha3' => 'col', 'name' => 'كولومبيا'),
            174 => array('id' => 174, 'alpha2' => 'km', 'alpha3' => 'com', 'name' => 'جزر القمر'),
            178 => array('id' => 178, 'alpha2' => 'cg', 'alpha3' => 'cog', 'name' => 'جمهورية الكونغو'),
            180 => array('id' => 180, 'alpha2' => 'cd', 'alpha3' => 'cod', 'name' => 'جمهورية الكونغو الديمقراطية'),
            188 => array('id' => 188, 'alpha2' => 'cr', 'alpha3' => 'cri', 'name' => 'كوستاريكا'),
            384 => array('id' => 384, 'alpha2' => 'ci', 'alpha3' => 'civ', 'name' => 'ساحل العاج'),
            191 => array('id' => 191, 'alpha2' => 'hr', 'alpha3' => 'hrv', 'name' => 'كرواتيا'),
            192 => array('id' => 192, 'alpha2' => 'cu', 'alpha3' => 'cub', 'name' => 'كوبا'),
            196 => array('id' => 196, 'alpha2' => 'cy', 'alpha3' => 'cyp', 'name' => 'قبرص'),
            203 => array('id' => 203, 'alpha2' => 'cz', 'alpha3' => 'cze', 'name' => 'جمهورية التشيك'),
            208 => array('id' => 208, 'alpha2' => 'dk', 'alpha3' => 'dnk', 'name' => 'الدنمارك'),
            262 => array('id' => 262, 'alpha2' => 'dj', 'alpha3' => 'dji', 'name' => 'جيبوتي'),
            212 => array('id' => 212, 'alpha2' => 'dm', 'alpha3' => 'dma', 'name' => 'دومينيكا'),
            214 => array('id' => 214, 'alpha2' => 'do', 'alpha3' => 'dom', 'name' => 'جمهورية الدومينيكان'),
            218 => array('id' => 218, 'alpha2' => 'ec', 'alpha3' => 'ecu', 'name' => 'الإكوادور'),
            818 => array('id' => 818, 'alpha2' => 'eg', 'alpha3' => 'egy', 'name' => 'مصر'),
            222 => array('id' => 222, 'alpha2' => 'sv', 'alpha3' => 'slv', 'name' => 'السلفادور'),
            226 => array('id' => 226, 'alpha2' => 'gq', 'alpha3' => 'gnq', 'name' => 'غينيا الاستوائية'),
            232 => array('id' => 232, 'alpha2' => 'er', 'alpha3' => 'eri', 'name' => 'إريتريا'),
            233 => array('id' => 233, 'alpha2' => 'ee', 'alpha3' => 'est', 'name' => 'إستونيا'),
            231 => array('id' => 231, 'alpha2' => 'et', 'alpha3' => 'eth', 'name' => 'إثيوبيا'),
            242 => array('id' => 242, 'alpha2' => 'fj', 'alpha3' => 'fji', 'name' => 'فيجي'),
            246 => array('id' => 246, 'alpha2' => 'fi', 'alpha3' => 'fin', 'name' => 'فنلندا'),
//            250 => array('id' => 250, 'alpha2' => 'fr', 'alpha3' => 'fra', 'name' => 'فرنسا'),
            266 => array('id' => 266, 'alpha2' => 'ga', 'alpha3' => 'gab', 'name' => 'الغابون'),
            270 => array('id' => 270, 'alpha2' => 'gm', 'alpha3' => 'gmb', 'name' => 'غامبيا'),
            268 => array('id' => 268, 'alpha2' => 'ge', 'alpha3' => 'geo', 'name' => 'جورجيا'),
            276 => array('id' => 276, 'alpha2' => 'de', 'alpha3' => 'deu', 'name' => 'ألمانيا'),
            288 => array('id' => 288, 'alpha2' => 'gh', 'alpha3' => 'gha', 'name' => 'غانا'),
            300 => array('id' => 300, 'alpha2' => 'gr', 'alpha3' => 'grc', 'name' => 'اليونان'),
            308 => array('id' => 308, 'alpha2' => 'gd', 'alpha3' => 'grd', 'name' => 'غرينادا'),
            320 => array('id' => 320, 'alpha2' => 'gt', 'alpha3' => 'gtm', 'name' => 'غواتيمالا'),
            324 => array('id' => 324, 'alpha2' => 'gn', 'alpha3' => 'gin', 'name' => 'غينيا'),
            624 => array('id' => 624, 'alpha2' => 'gw', 'alpha3' => 'gnb', 'name' => 'غينيا بيساو'),
            328 => array('id' => 328, 'alpha2' => 'gy', 'alpha3' => 'guy', 'name' => 'غيانا'),
            332 => array('id' => 332, 'alpha2' => 'ht', 'alpha3' => 'hti', 'name' => 'هايتي'),
            340 => array('id' => 340, 'alpha2' => 'hn', 'alpha3' => 'hnd', 'name' => 'هندوراس'),
            348 => array('id' => 348, 'alpha2' => 'hu', 'alpha3' => 'hun', 'name' => 'المجر'),
            352 => array('id' => 352, 'alpha2' => 'is', 'alpha3' => 'isl', 'name' => 'آيسلندا'),
            356 => array('id' => 356, 'alpha2' => 'in', 'alpha3' => 'ind', 'name' => 'الهند'),
            360 => array('id' => 360, 'alpha2' => 'id', 'alpha3' => 'idn', 'name' => 'إندونيسيا'),
            364 => array('id' => 364, 'alpha2' => 'ir', 'alpha3' => 'irn', 'name' => 'إيران'),
            368 => array('id' => 368, 'alpha2' => 'iq', 'alpha3' => 'irq', 'name' => 'العراق'),
            372 => array('id' => 372, 'alpha2' => 'ie', 'alpha3' => 'irl', 'name' => 'أيرلندا'),
//            376 => array('id' => 376, 'alpha2' => 'il', 'alpha3' => 'isr', 'name' => 'إسرائيل'),
            380 => array('id' => 380, 'alpha2' => 'it', 'alpha3' => 'ita', 'name' => 'إيطاليا'),
            388 => array('id' => 388, 'alpha2' => 'jm', 'alpha3' => 'jam', 'name' => 'جامايكا'),
            392 => array('id' => 392, 'alpha2' => 'jp', 'alpha3' => 'jpn', 'name' => 'اليابان'),
            400 => array('id' => 400, 'alpha2' => 'jo', 'alpha3' => 'jor', 'name' => 'الأردن'),
            398 => array('id' => 398, 'alpha2' => 'kz', 'alpha3' => 'kaz', 'name' => 'كازاخستان'),
            404 => array('id' => 404, 'alpha2' => 'ke', 'alpha3' => 'ken', 'name' => 'كينيا'),
            296 => array('id' => 296, 'alpha2' => 'ki', 'alpha3' => 'kir', 'name' => 'كيريباتي'),
            408 => array('id' => 408, 'alpha2' => 'kp', 'alpha3' => 'prk', 'name' => 'كوريا الشمالية'),
            410 => array('id' => 410, 'alpha2' => 'kr', 'alpha3' => 'kor', 'name' => 'كوريا الجنوبية'),
            414 => array('id' => 414, 'alpha2' => 'kw', 'alpha3' => 'kwt', 'name' => 'الكويت'),
            417 => array('id' => 417, 'alpha2' => 'kg', 'alpha3' => 'kgz', 'name' => 'قيرغيزستان'),
            418 => array('id' => 418, 'alpha2' => 'la', 'alpha3' => 'lao', 'name' => 'لاوس'),
            428 => array('id' => 428, 'alpha2' => 'lv', 'alpha3' => 'lva', 'name' => 'لاتفيا'),
            422 => array('id' => 422, 'alpha2' => 'lb', 'alpha3' => 'lbn', 'name' => 'لبنان'),
            426 => array('id' => 426, 'alpha2' => 'ls', 'alpha3' => 'lso', 'name' => 'ليسوتو'),
            430 => array('id' => 430, 'alpha2' => 'lr', 'alpha3' => 'lbr', 'name' => 'ليبيريا'),
            434 => array('id' => 434, 'alpha2' => 'ly', 'alpha3' => 'lby', 'name' => 'ليبيا'),
            438 => array('id' => 438, 'alpha2' => 'li', 'alpha3' => 'lie', 'name' => 'ليختنشتاين'),
            440 => array('id' => 440, 'alpha2' => 'lt', 'alpha3' => 'ltu', 'name' => 'ليتوانيا'),
            442 => array('id' => 442, 'alpha2' => 'lu', 'alpha3' => 'lux', 'name' => 'لوكسمبورغ'),
            807 => array('id' => 807, 'alpha2' => 'mk', 'alpha3' => 'mkd', 'name' => 'مقدونيا'),
            450 => array('id' => 450, 'alpha2' => 'mg', 'alpha3' => 'mdg', 'name' => 'مدغشقر'),
            454 => array('id' => 454, 'alpha2' => 'mw', 'alpha3' => 'mwi', 'name' => 'مالاوي'),
            458 => array('id' => 458, 'alpha2' => 'my', 'alpha3' => 'mys', 'name' => 'ماليزيا'),
            462 => array('id' => 462, 'alpha2' => 'mv', 'alpha3' => 'mdv', 'name' => 'جزر المالديف'),
            466 => array('id' => 466, 'alpha2' => 'ml', 'alpha3' => 'mli', 'name' => 'مالي'),
            470 => array('id' => 470, 'alpha2' => 'mt', 'alpha3' => 'mlt', 'name' => 'مالطا'),
            584 => array('id' => 584, 'alpha2' => 'mh', 'alpha3' => 'mhl', 'name' => 'جزر مارشال'),
            478 => array('id' => 478, 'alpha2' => 'mr', 'alpha3' => 'mrt', 'name' => 'موريتانيا'),
            480 => array('id' => 480, 'alpha2' => 'mu', 'alpha3' => 'mus', 'name' => 'موريشيوس'),
            484 => array('id' => 484, 'alpha2' => 'mx', 'alpha3' => 'mex', 'name' => 'المكسيك'),
            583 => array('id' => 583, 'alpha2' => 'fm', 'alpha3' => 'fsm', 'name' => 'ولايات ميكرونيسيا المتحدة'),
            504 => array('id' => 504, 'alpha2' => 'ma', 'alpha3' => 'mar', 'name' => 'المغرب'),
            498 => array('id' => 498, 'alpha2' => 'md', 'alpha3' => 'mda', 'name' => 'مولدوفا'),
            492 => array('id' => 492, 'alpha2' => 'mc', 'alpha3' => 'mco', 'name' => 'موناكو'),
            496 => array('id' => 496, 'alpha2' => 'mn', 'alpha3' => 'mng', 'name' => 'منغوليا'),
            499 => array('id' => 499, 'alpha2' => 'me', 'alpha3' => 'mne', 'name' => 'الجبل الأسود'),
            508 => array('id' => 508, 'alpha2' => 'mz', 'alpha3' => 'moz', 'name' => 'موزمبيق'),
            104 => array('id' => 104, 'alpha2' => 'mm', 'alpha3' => 'mmr', 'name' => 'ميانمار'),
            516 => array('id' => 516, 'alpha2' => 'na', 'alpha3' => 'nam', 'name' => 'ناميبيا'),
            520 => array('id' => 520, 'alpha2' => 'nr', 'alpha3' => 'nru', 'name' => 'ناورو'),
            524 => array('id' => 524, 'alpha2' => 'np', 'alpha3' => 'npl', 'name' => 'نيبال'),
            528 => array('id' => 528, 'alpha2' => 'nl', 'alpha3' => 'nld', 'name' => 'هولندا'),
            554 => array('id' => 554, 'alpha2' => 'nz', 'alpha3' => 'nzl', 'name' => 'نيوزيلندا'),
            558 => array('id' => 558, 'alpha2' => 'ni', 'alpha3' => 'nic', 'name' => 'نيكاراغوا'),
            562 => array('id' => 562, 'alpha2' => 'ne', 'alpha3' => 'ner', 'name' => 'النيجر'),
            566 => array('id' => 566, 'alpha2' => 'ng', 'alpha3' => 'nga', 'name' => 'نيجيريا'),
            578 => array('id' => 578, 'alpha2' => 'no', 'alpha3' => 'nor', 'name' => 'النرويج'),
            512 => array('id' => 512, 'alpha2' => 'om', 'alpha3' => 'omn', 'name' => 'عمان'),
            586 => array('id' => 586, 'alpha2' => 'pk', 'alpha3' => 'pak', 'name' => 'باكستان'),
            585 => array('id' => 585, 'alpha2' => 'pw', 'alpha3' => 'plw', 'name' => 'بالاو'),
            591 => array('id' => 591, 'alpha2' => 'pa', 'alpha3' => 'pan', 'name' => 'بنما'),
            598 => array('id' => 598, 'alpha2' => 'pg', 'alpha3' => 'png', 'name' => 'بابوا غينيا الجديدة'),
            600 => array('id' => 600, 'alpha2' => 'py', 'alpha3' => 'pry', 'name' => 'باراغواي'),
            604 => array('id' => 604, 'alpha2' => 'pe', 'alpha3' => 'per', 'name' => 'بيرو'),
            608 => array('id' => 608, 'alpha2' => 'ph', 'alpha3' => 'phl', 'name' => 'الفلبين'),
            616 => array('id' => 616, 'alpha2' => 'pl', 'alpha3' => 'pol', 'name' => 'بولندا'),
            620 => array('id' => 620, 'alpha2' => 'pt', 'alpha3' => 'prt', 'name' => 'البرتغال'),
            634 => array('id' => 634, 'alpha2' => 'qa', 'alpha3' => 'qat', 'name' => 'قطر'),
            642 => array('id' => 642, 'alpha2' => 'ro', 'alpha3' => 'rou', 'name' => 'رومانيا'),
            643 => array('id' => 643, 'alpha2' => 'ru', 'alpha3' => 'rus', 'name' => 'روسيا'),
            646 => array('id' => 646, 'alpha2' => 'rw', 'alpha3' => 'rwa', 'name' => 'رواندا'),
            659 => array('id' => 659, 'alpha2' => 'kn', 'alpha3' => 'kna', 'name' => 'سانت كيتس ونيفيس'),
            662 => array('id' => 662, 'alpha2' => 'lc', 'alpha3' => 'lca', 'name' => 'سانت لوسيا'),
            670 => array('id' => 670, 'alpha2' => 'vc', 'alpha3' => 'vct', 'name' => 'سانت فينسنت والغرينادين'),
            882 => array('id' => 882, 'alpha2' => 'ws', 'alpha3' => 'wsm', 'name' => 'ساموا'),
            674 => array('id' => 674, 'alpha2' => 'sm', 'alpha3' => 'smr', 'name' => 'سان مارينو'),
            678 => array('id' => 678, 'alpha2' => 'st', 'alpha3' => 'stp', 'name' => 'ساو تومي وبرينسيب'),
            682 => array('id' => 682, 'alpha2' => 'sa', 'alpha3' => 'sau', 'name' => 'السعودية'),
            686 => array('id' => 686, 'alpha2' => 'sn', 'alpha3' => 'sen', 'name' => 'السنغال'),
            688 => array('id' => 688, 'alpha2' => 'rs', 'alpha3' => 'srb', 'name' => 'صربيا'),
            690 => array('id' => 690, 'alpha2' => 'sc', 'alpha3' => 'syc', 'name' => 'سيشل'),
            694 => array('id' => 694, 'alpha2' => 'sl', 'alpha3' => 'sle', 'name' => 'سيراليون'),
            702 => array('id' => 702, 'alpha2' => 'sg', 'alpha3' => 'sgp', 'name' => 'سنغافورة'),
            703 => array('id' => 703, 'alpha2' => 'sk', 'alpha3' => 'svk', 'name' => 'سلوفاكيا'),
            705 => array('id' => 705, 'alpha2' => 'si', 'alpha3' => 'svn', 'name' => 'سلوفينيا'),
            90 => array('id' => 90, 'alpha2' => 'sb', 'alpha3' => 'slb', 'name' => 'جزر سليمان'),
            706 => array('id' => 706, 'alpha2' => 'so', 'alpha3' => 'som', 'name' => 'الصومال'),
            710 => array('id' => 710, 'alpha2' => 'za', 'alpha3' => 'zaf', 'name' => 'جنوب إفريقيا'),
            728 => array('id' => 728, 'alpha2' => 'ss', 'alpha3' => 'ssd', 'name' => 'جنوب السودان'),
            724 => array('id' => 724, 'alpha2' => 'es', 'alpha3' => 'esp', 'name' => 'إسبانيا'),
            144 => array('id' => 144, 'alpha2' => 'lk', 'alpha3' => 'lka', 'name' => 'سريلانكا'),
            729 => array('id' => 729, 'alpha2' => 'sd', 'alpha3' => 'sdn', 'name' => 'السودان'),
            740 => array('id' => 740, 'alpha2' => 'sr', 'alpha3' => 'sur', 'name' => 'سورينام'),
            748 => array('id' => 748, 'alpha2' => 'sz', 'alpha3' => 'swz', 'name' => 'إسواتيني'),
            752 => array('id' => 752, 'alpha2' => 'se', 'alpha3' => 'swe', 'name' => 'السويد'),
            756 => array('id' => 756, 'alpha2' => 'ch', 'alpha3' => 'che', 'name' => 'سويسرا'),
            760 => array('id' => 760, 'alpha2' => 'sy', 'alpha3' => 'syr', 'name' => 'سوريا'),
            762 => array('id' => 762, 'alpha2' => 'tj', 'alpha3' => 'tjk', 'name' => 'طاجيكستان'),
            834 => array('id' => 834, 'alpha2' => 'tz', 'alpha3' => 'tza', 'name' => 'تنزانيا'),
            764 => array('id' => 764, 'alpha2' => 'th', 'alpha3' => 'tha', 'name' => 'تايلاند'),
            626 => array('id' => 626, 'alpha2' => 'tl', 'alpha3' => 'tls', 'name' => 'تيمور الشرقية'),
            768 => array('id' => 768, 'alpha2' => 'tg', 'alpha3' => 'tgo', 'name' => 'توغو'),
            776 => array('id' => 776, 'alpha2' => 'to', 'alpha3' => 'ton', 'name' => 'تونغا'),
            780 => array('id' => 780, 'alpha2' => 'tt', 'alpha3' => 'tto', 'name' => 'ترينيداد وتوباغو'),
            788 => array('id' => 788, 'alpha2' => 'tn', 'alpha3' => 'tun', 'name' => 'تونس'),
            792 => array('id' => 792, 'alpha2' => 'tr', 'alpha3' => 'tur', 'name' => 'تركيا'),
            795 => array('id' => 795, 'alpha2' => 'tm', 'alpha3' => 'tkm', 'name' => 'تركمانستان'),
            798 => array('id' => 798, 'alpha2' => 'tv', 'alpha3' => 'tuv', 'name' => 'توفالو'),
            800 => array('id' => 800, 'alpha2' => 'ug', 'alpha3' => 'uga', 'name' => 'أوغندا'),
            804 => array('id' => 804, 'alpha2' => 'ua', 'alpha3' => 'ukr', 'name' => 'أوكرانيا'),
            784 => array('id' => 784, 'alpha2' => 'ae', 'alpha3' => 'are', 'name' => 'الإمارات العربية المتحدة'),
            826 => array('id' => 826, 'alpha2' => 'gb', 'alpha3' => 'gbr', 'name' => 'المملكة المتحدة'),
            840 => array('id' => 840, 'alpha2' => 'us', 'alpha3' => 'usa', 'name' => 'الولايات المتحدة'),
            858 => array('id' => 858, 'alpha2' => 'uy', 'alpha3' => 'ury', 'name' => 'الأوروغواي'),
            860 => array('id' => 860, 'alpha2' => 'uz', 'alpha3' => 'uzb', 'name' => 'أوزبكستان'),
            548 => array('id' => 548, 'alpha2' => 'vu', 'alpha3' => 'vut', 'name' => 'فانواتو'),
            862 => array('id' => 862, 'alpha2' => 've', 'alpha3' => 'ven', 'name' => 'فنزويلا'),
            704 => array('id' => 704, 'alpha2' => 'vn', 'alpha3' => 'vnm', 'name' => 'فيتنام'),
            887 => array('id' => 887, 'alpha2' => 'ye', 'alpha3' => 'yem', 'name' => 'اليمن'),
            894 => array('id' => 894, 'alpha2' => 'zm', 'alpha3' => 'zmb', 'name' => 'زامبيا'),
            716 => array('id' => 716, 'alpha2' => 'zw', 'alpha3' => 'zwe', 'name' => 'زيمبابوي'),
        );
        foreach ( $countries_ar  as $country ){
             Country::create([
                 'alpha2'  => $country['alpha2'],
                 'alpha3'  => $country['alpha3'],
                 'ar' => [
                     'name' => $country['name']
                 ],
                 'en' => [
                     'name' => 'Saudi Arabia'
                 ]
             ]);
        }

        $countries_en = array(
            array('id' => 275, 'alpha2' => 'ps', 'alpha3' => 'pse', 'name' => 'Palestine'),
            array('id' => 4, 'alpha2' => 'af', 'alpha3' => 'afg', 'name' => 'Afghanistan'),
            array('id' => 8, 'alpha2' => 'al', 'alpha3' => 'alb', 'name' => 'Albania'),
            array('id' => 12, 'alpha2' => 'dz', 'alpha3' => 'dza', 'name' => 'Algeria'),
            array('id' => 20, 'alpha2' => 'ad', 'alpha3' => 'and', 'name' => 'Andorra'),
            array('id' => 24, 'alpha2' => 'ao', 'alpha3' => 'ago', 'name' => 'Angola'),
            array('id' => 28, 'alpha2' => 'ag', 'alpha3' => 'atg', 'name' => 'Antigua and Barbuda'),
            array('id' => 32, 'alpha2' => 'ar', 'alpha3' => 'arg', 'name' => 'Argentina'),
            array('id' => 51, 'alpha2' => 'am', 'alpha3' => 'arm', 'name' => 'Armenia'),
            array('id' => 36, 'alpha2' => 'au', 'alpha3' => 'aus', 'name' => 'Australia'),
            array('id' => 40, 'alpha2' => 'at', 'alpha3' => 'aut', 'name' => 'Austria'),
            array('id' => 31, 'alpha2' => 'az', 'alpha3' => 'aze', 'name' => 'Azerbaijan'),
            array('id' => 44, 'alpha2' => 'bs', 'alpha3' => 'bhs', 'name' => 'Bahamas'),
            array('id' => 48, 'alpha2' => 'bh', 'alpha3' => 'bhr', 'name' => 'Bahrain'),
            array('id' => 50, 'alpha2' => 'bd', 'alpha3' => 'bgd', 'name' => 'Bangladesh'),
            array('id' => 52, 'alpha2' => 'bb', 'alpha3' => 'brb', 'name' => 'Barbados'),
            array('id' => 112, 'alpha2' => 'by', 'alpha3' => 'blr', 'name' => 'Belarus'),
            array('id' => 56, 'alpha2' => 'be', 'alpha3' => 'bel', 'name' => 'Belgium'),
            array('id' => 84, 'alpha2' => 'bz', 'alpha3' => 'blz', 'name' => 'Belize'),
            array('id' => 204, 'alpha2' => 'bj', 'alpha3' => 'ben', 'name' => 'Benin'),
            array('id' => 64, 'alpha2' => 'bt', 'alpha3' => 'btn', 'name' => 'Bhutan'),
            array('id' => 68, 'alpha2' => 'bo', 'alpha3' => 'bol', 'name' => 'Bolivia (Plurinational State of)'),
            array('id' => 70, 'alpha2' => 'ba', 'alpha3' => 'bih', 'name' => 'Bosnia and Herzegovina'),
            array('id' => 72, 'alpha2' => 'bw', 'alpha3' => 'bwa', 'name' => 'Botswana'),
            array('id' => 76, 'alpha2' => 'br', 'alpha3' => 'bra', 'name' => 'Brazil'),
            array('id' => 96, 'alpha2' => 'bn', 'alpha3' => 'brn', 'name' => 'Brunei Darussalam'),
            array('id' => 100, 'alpha2' => 'bg', 'alpha3' => 'bgr', 'name' => 'Bulgaria'),
            array('id' => 854, 'alpha2' => 'bf', 'alpha3' => 'bfa', 'name' => 'Burkina Faso'),
            array('id' => 108, 'alpha2' => 'bi', 'alpha3' => 'bdi', 'name' => 'Burundi'),
            array('id' => 132, 'alpha2' => 'cv', 'alpha3' => 'cpv', 'name' => 'Cabo Verde'),
            array('id' => 116, 'alpha2' => 'kh', 'alpha3' => 'khm', 'name' => 'Cambodia'),
            array('id' => 120, 'alpha2' => 'cm', 'alpha3' => 'cmr', 'name' => 'Cameroon'),
            array('id' => 124, 'alpha2' => 'ca', 'alpha3' => 'can', 'name' => 'Canada'),
            array('id' => 140, 'alpha2' => 'cf', 'alpha3' => 'caf', 'name' => 'Central African Republic'),
            array('id' => 148, 'alpha2' => 'td', 'alpha3' => 'tcd', 'name' => 'Chad'),
            array('id' => 152, 'alpha2' => 'cl', 'alpha3' => 'chl', 'name' => 'Chile'),
            array('id' => 156, 'alpha2' => 'cn', 'alpha3' => 'chn', 'name' => 'China'),
            array('id' => 170, 'alpha2' => 'co', 'alpha3' => 'col', 'name' => 'Colombia'),
            array('id' => 174, 'alpha2' => 'km', 'alpha3' => 'com', 'name' => 'Comoros'),
            array('id' => 178, 'alpha2' => 'cg', 'alpha3' => 'cog', 'name' => 'Congo'),
            array('id' => 180, 'alpha2' => 'cd', 'alpha3' => 'cod', 'name' => 'Congo, Democratic Republic of the'),
            array('id' => 188, 'alpha2' => 'cr', 'alpha3' => 'cri', 'name' => 'Costa Rica'),
            array('id' => 384, 'alpha2' => 'ci', 'alpha3' => 'civ', 'name' => 'Côte d\'Ivoire'),
            array('id' => 191, 'alpha2' => 'hr', 'alpha3' => 'hrv', 'name' => 'Croatia'),
            array('id' => 192, 'alpha2' => 'cu', 'alpha3' => 'cub', 'name' => 'Cuba'),
            array('id' => 196, 'alpha2' => 'cy', 'alpha3' => 'cyp', 'name' => 'Cyprus'),
            array('id' => 203, 'alpha2' => 'cz', 'alpha3' => 'cze', 'name' => 'Czechia'),
            array('id' => 208, 'alpha2' => 'dk', 'alpha3' => 'dnk', 'name' => 'Denmark'),
            array('id' => 262, 'alpha2' => 'dj', 'alpha3' => 'dji', 'name' => 'Djibouti'),
            array('id' => 212, 'alpha2' => 'dm', 'alpha3' => 'dma', 'name' => 'Dominica'),
            array('id' => 214, 'alpha2' => 'do', 'alpha3' => 'dom', 'name' => 'Dominican Republic'),
            array('id' => 218, 'alpha2' => 'ec', 'alpha3' => 'ecu', 'name' => 'Ecuador'),
            array('id' => 818, 'alpha2' => 'eg', 'alpha3' => 'egy', 'name' => 'Egypt'),
            array('id' => 222, 'alpha2' => 'sv', 'alpha3' => 'slv', 'name' => 'El Salvador'),
            array('id' => 226, 'alpha2' => 'gq', 'alpha3' => 'gnq', 'name' => 'Equatorial Guinea'),
            array('id' => 232, 'alpha2' => 'er', 'alpha3' => 'eri', 'name' => 'Eritrea'),
            array('id' => 233, 'alpha2' => 'ee', 'alpha3' => 'est', 'name' => 'Estonia'),
            array('id' => 748, 'alpha2' => 'sz', 'alpha3' => 'swz', 'name' => 'Eswatini'),
            array('id' => 231, 'alpha2' => 'et', 'alpha3' => 'eth', 'name' => 'Ethiopia'),
            array('id' => 242, 'alpha2' => 'fj', 'alpha3' => 'fji', 'name' => 'Fiji'),
            array('id' => 246, 'alpha2' => 'fi', 'alpha3' => 'fin', 'name' => 'Finland'),
//             array('id' => 250, 'alpha2' => 'fr', 'alpha3' => 'fra', 'name' => 'France'),
            array('id' => 266, 'alpha2' => 'ga', 'alpha3' => 'gab', 'name' => 'Gabon'),
            array('id' => 270, 'alpha2' => 'gm', 'alpha3' => 'gmb', 'name' => 'Gambia'),
            array('id' => 268, 'alpha2' => 'ge', 'alpha3' => 'geo', 'name' => 'Georgia'),
            array('id' => 276, 'alpha2' => 'de', 'alpha3' => 'deu', 'name' => 'Germany'),
            array('id' => 288, 'alpha2' => 'gh', 'alpha3' => 'gha', 'name' => 'Ghana'),
            array('id' => 300, 'alpha2' => 'gr', 'alpha3' => 'grc', 'name' => 'Greece'),
            array('id' => 308, 'alpha2' => 'gd', 'alpha3' => 'grd', 'name' => 'Grenada'),
            array('id' => 320, 'alpha2' => 'gt', 'alpha3' => 'gtm', 'name' => 'Guatemala'),
            array('id' => 324, 'alpha2' => 'gn', 'alpha3' => 'gin', 'name' => 'Guinea'),
            array('id' => 624, 'alpha2' => 'gw', 'alpha3' => 'gnb', 'name' => 'Guinea-Bissau'),
            array('id' => 328, 'alpha2' => 'gy', 'alpha3' => 'guy', 'name' => 'Guyana'),
            array('id' => 332, 'alpha2' => 'ht', 'alpha3' => 'hti', 'name' => 'Haiti'),
            array('id' => 340, 'alpha2' => 'hn', 'alpha3' => 'hnd', 'name' => 'Honduras'),
            array('id' => 348, 'alpha2' => 'hu', 'alpha3' => 'hun', 'name' => 'Hungary'),
            array('id' => 352, 'alpha2' => 'is', 'alpha3' => 'isl', 'name' => 'Iceland'),
            array('id' => 356, 'alpha2' => 'in', 'alpha3' => 'ind', 'name' => 'India'),
            array('id' => 360, 'alpha2' => 'id', 'alpha3' => 'idn', 'name' => 'Indonesia'),
            array('id' => 364, 'alpha2' => 'ir', 'alpha3' => 'irn', 'name' => 'Iran (Islamic Republic of)'),
            array('id' => 368, 'alpha2' => 'iq', 'alpha3' => 'irq', 'name' => 'Iraq'),
            array('id' => 372, 'alpha2' => 'ie', 'alpha3' => 'irl', 'name' => 'Ireland'),
//            376 => array('id' => 376, 'alpha2' => 'il', 'alpha3' => 'isr', 'name' => 'Israel'),
            array('id' => 380, 'alpha2' => 'it', 'alpha3' => 'ita', 'name' => 'Italy'),
            array('id' => 388, 'alpha2' => 'jm', 'alpha3' => 'jam', 'name' => 'Jamaica'),
            array('id' => 392, 'alpha2' => 'jp', 'alpha3' => 'jpn', 'name' => 'Japan'),
            array('id' => 400, 'alpha2' => 'jo', 'alpha3' => 'jor', 'name' => 'Jordan'),
            array('id' => 398, 'alpha2' => 'kz', 'alpha3' => 'kaz', 'name' => 'Kazakhstan'),
            array('id' => 404, 'alpha2' => 'ke', 'alpha3' => 'ken', 'name' => 'Kenya'),
            array('id' => 296, 'alpha2' => 'ki', 'alpha3' => 'kir', 'name' => 'Kiribati'),
            array('id' => 408, 'alpha2' => 'kp', 'alpha3' => 'prk', 'name' => 'Korea (Democratic People\'s Republic of)'),
            array('id' => 410, 'alpha2' => 'kr', 'alpha3' => 'kor', 'name' => 'Korea, Republic of'),
            array('id' => 414, 'alpha2' => 'kw', 'alpha3' => 'kwt', 'name' => 'Kuwait'),
            array('id' => 417, 'alpha2' => 'kg', 'alpha3' => 'kgz', 'name' => 'Kyrgyzstan'),
            array('id' => 418, 'alpha2' => 'la', 'alpha3' => 'lao', 'name' => 'Lao People\'s Democratic Republic'),
            array('id' => 428, 'alpha2' => 'lv', 'alpha3' => 'lva', 'name' => 'Latvia'),
            array('id' => 422, 'alpha2' => 'lb', 'alpha3' => 'lbn', 'name' => 'Lebanon'),
            array('id' => 426, 'alpha2' => 'ls', 'alpha3' => 'lso', 'name' => 'Lesotho'),
            array('id' => 430, 'alpha2' => 'lr', 'alpha3' => 'lbr', 'name' => 'Liberia'),
            array('id' => 434, 'alpha2' => 'ly', 'alpha3' => 'lby', 'name' => 'Libya'),
            array('id' => 438, 'alpha2' => 'li', 'alpha3' => 'lie', 'name' => 'Liechtenstein'),
            array('id' => 440, 'alpha2' => 'lt', 'alpha3' => 'ltu', 'name' => 'Lithuania'),
            array('id' => 442, 'alpha2' => 'lu', 'alpha3' => 'lux', 'name' => 'Luxembourg'),
            array('id' => 450, 'alpha2' => 'mg', 'alpha3' => 'mdg', 'name' => 'Madagascar'),
            array('id' => 454, 'alpha2' => 'mw', 'alpha3' => 'mwi', 'name' => 'Malawi'),
            array('id' => 458, 'alpha2' => 'my', 'alpha3' => 'mys', 'name' => 'Malaysia'),
            array('id' => 462, 'alpha2' => 'mv', 'alpha3' => 'mdv', 'name' => 'Maldives'),
            array('id' => 466, 'alpha2' => 'ml', 'alpha3' => 'mli', 'name' => 'Mali'),
            array('id' => 470, 'alpha2' => 'mt', 'alpha3' => 'mlt', 'name' => 'Malta'),
            array('id' => 584, 'alpha2' => 'mh', 'alpha3' => 'mhl', 'name' => 'Marshall Islands'),
            array('id' => 478, 'alpha2' => 'mr', 'alpha3' => 'mrt', 'name' => 'Mauritania'),
            array('id' => 480, 'alpha2' => 'mu', 'alpha3' => 'mus', 'name' => 'Mauritius'),
            array('id' => 484, 'alpha2' => 'mx', 'alpha3' => 'mex', 'name' => 'Mexico'),
            array('id' => 583, 'alpha2' => 'fm', 'alpha3' => 'fsm', 'name' => 'Micronesia (Federated States of)'),
            array('id' => 498, 'alpha2' => 'md', 'alpha3' => 'mda', 'name' => 'Moldova, Republic of'),
            array('id' => 492, 'alpha2' => 'mc', 'alpha3' => 'mco', 'name' => 'Monaco'),
            array('id' => 496, 'alpha2' => 'mn', 'alpha3' => 'mng', 'name' => 'Mongolia'),
            array('id' => 499, 'alpha2' => 'me', 'alpha3' => 'mne', 'name' => 'Montenegro'),
            array('id' => 504, 'alpha2' => 'ma', 'alpha3' => 'mar', 'name' => 'Morocco'),
            array('id' => 508, 'alpha2' => 'mz', 'alpha3' => 'moz', 'name' => 'Mozambique'),
            array('id' => 104, 'alpha2' => 'mm', 'alpha3' => 'mmr', 'name' => 'Myanmar'),
            array('id' => 516, 'alpha2' => 'na', 'alpha3' => 'nam', 'name' => 'Namibia'),
            array('id' => 520, 'alpha2' => 'nr', 'alpha3' => 'nru', 'name' => 'Nauru'),
            array('id' => 524, 'alpha2' => 'np', 'alpha3' => 'npl', 'name' => 'Nepal'),
            array('id' => 528, 'alpha2' => 'nl', 'alpha3' => 'nld', 'name' => 'Netherlands'),
            array('id' => 554, 'alpha2' => 'nz', 'alpha3' => 'nzl', 'name' => 'New Zealand'),
            array('id' => 558, 'alpha2' => 'ni', 'alpha3' => 'nic', 'name' => 'Nicaragua'),
            array('id' => 562, 'alpha2' => 'ne', 'alpha3' => 'ner', 'name' => 'Niger'),
            array('id' => 566, 'alpha2' => 'ng', 'alpha3' => 'nga', 'name' => 'Nigeria'),
            array('id' => 807, 'alpha2' => 'mk', 'alpha3' => 'mkd', 'name' => 'North Macedonia'),
            array('id' => 578, 'alpha2' => 'no', 'alpha3' => 'nor', 'name' => 'Norway'),
            array('id' => 512, 'alpha2' => 'om', 'alpha3' => 'omn', 'name' => 'Oman'),
            array('id' => 586, 'alpha2' => 'pk', 'alpha3' => 'pak', 'name' => 'Pakistan'),
            array('id' => 585, 'alpha2' => 'pw', 'alpha3' => 'plw', 'name' => 'Palau'),
            array('id' => 591, 'alpha2' => 'pa', 'alpha3' => 'pan', 'name' => 'Panama'),
            array('id' => 598, 'alpha2' => 'pg', 'alpha3' => 'png', 'name' => 'Papua New Guinea'),
            array('id' => 600, 'alpha2' => 'py', 'alpha3' => 'pry', 'name' => 'Paraguay'),
            array('id' => 604, 'alpha2' => 'pe', 'alpha3' => 'per', 'name' => 'Peru'),
            array('id' => 608, 'alpha2' => 'ph', 'alpha3' => 'phl', 'name' => 'Philippines'),
            array('id' => 616, 'alpha2' => 'pl', 'alpha3' => 'pol', 'name' => 'Poland'),
            array('id' => 620, 'alpha2' => 'pt', 'alpha3' => 'prt', 'name' => 'Portugal'),
            array('id' => 634, 'alpha2' => 'qa', 'alpha3' => 'qat', 'name' => 'Qatar'),
            array('id' => 642, 'alpha2' => 'ro', 'alpha3' => 'rou', 'name' => 'Romania'),
            array('id' => 643, 'alpha2' => 'ru', 'alpha3' => 'rus', 'name' => 'Russian Federation'),
            array('id' => 646, 'alpha2' => 'rw', 'alpha3' => 'rwa', 'name' => 'Rwanda'),
            array('id' => 659, 'alpha2' => 'kn', 'alpha3' => 'kna', 'name' => 'Saint Kitts and Nevis'),
            array('id' => 662, 'alpha2' => 'lc', 'alpha3' => 'lca', 'name' => 'Saint Lucia'),
            array('id' => 670, 'alpha2' => 'vc', 'alpha3' => 'vct', 'name' => 'Saint Vincent and the Grenadines'),
            array('id' => 882, 'alpha2' => 'ws', 'alpha3' => 'wsm', 'name' => 'Samoa'),
            array('id' => 674, 'alpha2' => 'sm', 'alpha3' => 'smr', 'name' => 'San Marino'),
            array('id' => 678, 'alpha2' => 'st', 'alpha3' => 'stp', 'name' => 'Sao Tome and Principe'),
            array('id' => 682, 'alpha2' => 'sa', 'alpha3' => 'sau', 'name' => 'Saudi Arabia'),
            array('id' => 686, 'alpha2' => 'sn', 'alpha3' => 'sen', 'name' => 'Senegal'),
            array('id' => 688, 'alpha2' => 'rs', 'alpha3' => 'srb', 'name' => 'Serbia'),
            array('id' => 690, 'alpha2' => 'sc', 'alpha3' => 'syc', 'name' => 'Seychelles'),
            array('id' => 694, 'alpha2' => 'sl', 'alpha3' => 'sle', 'name' => 'Sierra Leone'),
            array('id' => 702, 'alpha2' => 'sg', 'alpha3' => 'sgp', 'name' => 'Singapore'),
            array('id' => 703, 'alpha2' => 'sk', 'alpha3' => 'svk', 'name' => 'Slovakia'),
            array('id' => 705, 'alpha2' => 'si', 'alpha3' => 'svn', 'name' => 'Slovenia'),
            array('id' => 90, 'alpha2' => 'sb', 'alpha3' => 'slb', 'name' => 'Solomon Islands'),
            array('id' => 706, 'alpha2' => 'so', 'alpha3' => 'som', 'name' => 'Somalia'),
            array('id' => 710, 'alpha2' => 'za', 'alpha3' => 'zaf', 'name' => 'South Africa'),
            array('id' => 728, 'alpha2' => 'ss', 'alpha3' => 'ssd', 'name' => 'South Sudan'),
            array('id' => 724, 'alpha2' => 'es', 'alpha3' => 'esp', 'name' => 'Spain'),
            array('id' => 144, 'alpha2' => 'lk', 'alpha3' => 'lka', 'name' => 'Sri Lanka'),
            array('id' => 729, 'alpha2' => 'sd', 'alpha3' => 'sdn', 'name' => 'Sudan'),
            array('id' => 740, 'alpha2' => 'sr', 'alpha3' => 'sur', 'name' => 'Suriname'),
            array('id' => 752, 'alpha2' => 'se', 'alpha3' => 'swe', 'name' => 'Sweden'),
            array('id' => 756, 'alpha2' => 'ch', 'alpha3' => 'che', 'name' => 'Switzerland'),
            array('id' => 760, 'alpha2' => 'sy', 'alpha3' => 'syr', 'name' => 'Syrian Arab Republic'),
            array('id' => 762, 'alpha2' => 'tj', 'alpha3' => 'tjk', 'name' => 'Tajikistan'),
            array('id' => 834, 'alpha2' => 'tz', 'alpha3' => 'tza', 'name' => 'Tanzania, United Republic of'),
            array('id' => 764, 'alpha2' => 'th', 'alpha3' => 'tha', 'name' => 'Thailand'),
            array('id' => 626, 'alpha2' => 'tl', 'alpha3' => 'tls', 'name' => 'Timor-Leste'),
            array('id' => 768, 'alpha2' => 'tg', 'alpha3' => 'tgo', 'name' => 'Togo'),
            array('id' => 776, 'alpha2' => 'to', 'alpha3' => 'ton', 'name' => 'Tonga'),
            array('id' => 780, 'alpha2' => 'tt', 'alpha3' => 'tto', 'name' => 'Trinidad and Tobago'),
            array('id' => 788, 'alpha2' => 'tn', 'alpha3' => 'tun', 'name' => 'Tunisia'),
            array('id' => 792, 'alpha2' => 'tr', 'alpha3' => 'tur', 'name' => 'Türkiye'),
            array('id' => 795, 'alpha2' => 'tm', 'alpha3' => 'tkm', 'name' => 'Turkmenistan'),
            array('id' => 798, 'alpha2' => 'tv', 'alpha3' => 'tuv', 'name' => 'Tuvalu'),
            array('id' => 800, 'alpha2' => 'ug', 'alpha3' => 'uga', 'name' => 'Uganda'),
            array('id' => 804, 'alpha2' => 'ua', 'alpha3' => 'ukr', 'name' => 'Ukraine'),
            array('id' => 784, 'alpha2' => 'ae', 'alpha3' => 'are', 'name' => 'United Arab Emirates'),
            array('id' => 826, 'alpha2' => 'gb', 'alpha3' => 'gbr', 'name' => 'United Kingdom of Great Britain and Northern Ireland'),
            array('id' => 840, 'alpha2' => 'us', 'alpha3' => 'usa', 'name' => 'United States of America'),
            array('id' => 858, 'alpha2' => 'uy', 'alpha3' => 'ury', 'name' => 'Uruguay'),
            array('id' => 860, 'alpha2' => 'uz', 'alpha3' => 'uzb', 'name' => 'Uzbekistan'),
            array('id' => 548, 'alpha2' => 'vu', 'alpha3' => 'vut', 'name' => 'Vanuatu'),
            array('id' => 862, 'alpha2' => 've', 'alpha3' => 'ven', 'name' => 'Venezuela (Bolivarian Republic of)'),
            array('id' => 704, 'alpha2' => 'vn', 'alpha3' => 'vnm', 'name' => 'Viet Nam'),
            array('id' => 887, 'alpha2' => 'ye', 'alpha3' => 'yem', 'name' => 'Yemen'),
            array('id' => 894, 'alpha2' => 'zm', 'alpha3' => 'zmb', 'name' => 'Zambia'),
            array('id' => 716, 'alpha2' => 'zw', 'alpha3' => 'zwe', 'name' => 'Zimbabwe'),
        );
        foreach ( $countries_en  as $country ){
            $store_country = Country::where('alpha2' , $country['alpha2'])
                ->where('alpha3' , $country['alpha3'])->first();
            $store_country->update([
                'en' => [
                    'name' => $country['name']
                ]
            ]);
        }

        return sizeof( $countries_ar );
    }













    //    public function storeCountries(){
//         $countries_ar =  array(
//             array('id' => 4  , 'alpha2' => 'af', 'alpha3' => 'afg', 'name' => 'أفغانستان'),
//             array('id' => 248, 'alpha2' => 'ax', 'alpha3' => 'ala', 'name' => 'جزر أولاند'),
//             array('id' => 8  , 'alpha2' => 'al', 'alpha3' => 'alb', 'name' => 'ألبانيا'),
//             array('id' => 12 , 'alpha2' => 'dz', 'alpha3' => 'dza', 'name' => 'الجزائر'),
//             array('id' => 16 , 'alpha2' => 'as', 'alpha3' => 'asm', 'name' => 'ساموا الأمريكية'),
//             array('id' => 20 , 'alpha2' => 'ad', 'alpha3' => 'and', 'name' => 'أندورا'),
//             array('id' => 24 , 'alpha2' => 'ao', 'alpha3' => 'ago', 'name' => 'أنغولا'),
//             array('id' => 660, 'alpha2' => 'ai', 'alpha3' => 'aia', 'name' => 'أنغويلا'),
//             array('id' => 10 , 'alpha2' => 'aq', 'alpha3' => 'ata', 'name' => 'القارة القطبية الجنوبية'),
//             array('id' => 28 , 'alpha2' => 'ag', 'alpha3' => 'atg', 'name' => 'أنتيغوا وباربودا'),
//             array('id' => 32 , 'alpha2' => 'ar', 'alpha3' => 'arg', 'name' => 'الأرجنتين'),
//             array('id' => 51 , 'alpha2' => 'am', 'alpha3' => 'arm', 'name' => 'أرمينيا'),
//             array('id' => 533, 'alpha2' => 'aw', 'alpha3' => 'abw', 'name' => 'أروبا'),
//             array('id' => 36 , 'alpha2' => 'au', 'alpha3' => 'aus', 'name' => 'أستراليا'),
//             array('id' => 40 , 'alpha2' => 'at', 'alpha3' => 'aut', 'name' => 'النمسا'),
//             array('id' => 31 , 'alpha2' => 'az', 'alpha3' => 'aze', 'name' => 'أذربيجان'),
//             array('id' => 44 , 'alpha2' => 'bs', 'alpha3' => 'bhs', 'name' => 'باهاماس'),
//             array('id' => 48 , 'alpha2' => 'bh', 'alpha3' => 'bhr', 'name' => 'البحرين'),
//             array('id' => 50 , 'alpha2' => 'bd', 'alpha3' => 'bgd', 'name' => 'بنغلاديش'),
//             array('id' => 52 , 'alpha2' => 'bb', 'alpha3' => 'brb', 'name' => 'باربادوس'),
//             array('id' => 112, 'alpha2' => 'by', 'alpha3' => 'blr', 'name' => 'بيلاروس'),
//             array('id' => 56 , 'alpha2' => 'be', 'alpha3' => 'bel', 'name' => 'بلجيكا'),
//             array('id' => 84 , 'alpha2' => 'bz', 'alpha3' => 'blz', 'name' => 'بليز'),
//             array('id' => 204, 'alpha2' => 'bj', 'alpha3' => 'ben', 'name' => 'بنين'),
//             array('id' => 60 , 'alpha2' => 'bm', 'alpha3' => 'bmu', 'name' => 'برمودا'),
//             array('id' => 64 , 'alpha2' => 'bt', 'alpha3' => 'btn', 'name' => 'بوتان'),
//             array('id' => 68 , 'alpha2' => 'bo', 'alpha3' => 'bol', 'name' => 'بوليفيا'),
//             array('id' => 535, 'alpha2' => 'bq', 'alpha3' => 'bes', 'name' => 'الجزر الكاريبية الهولندية'),
//             array('id' => 70 , 'alpha2' => 'ba', 'alpha3' => 'bih', 'name' => 'البوسنة والهرسك'),
//             array('id' => 72 , 'alpha2' => 'bw', 'alpha3' => 'bwa', 'name' => 'بوتسوانا'),
//             array('id' => 74 , 'alpha2' => 'bv', 'alpha3' => 'bvt', 'name' => 'جزيرة بوفيه'),
//             array('id' => 76 , 'alpha2' => 'br', 'alpha3' => 'bra', 'name' => 'البرازيل'),
//             array('id' => 86 , 'alpha2' => 'io', 'alpha3' => 'iot', 'name' => 'إقليم المحيط الهندي البريطاني'),
//             array('id' => 96 , 'alpha2' => 'bn', 'alpha3' => 'brn', 'name' => 'بروناي'),
//             array('id' => 100, 'alpha2' => 'bg', 'alpha3' => 'bgr', 'name' => 'بلغاريا'),
//             array('id' => 854, 'alpha2' => 'bf', 'alpha3' => 'bfa', 'name' => 'بوركينا فاسو'),
//             array('id' => 108, 'alpha2' => 'bi', 'alpha3' => 'bdi', 'name' => 'بوروندي'),
//             array('id' => 116, 'alpha2' => 'kh', 'alpha3' => 'khm', 'name' => 'كمبوديا'),
//             array('id' => 120, 'alpha2' => 'cm', 'alpha3' => 'cmr', 'name' => 'الكاميرون'),
//             array('id' => 124, 'alpha2' => 'ca', 'alpha3' => 'can', 'name' => 'كندا'),
//             array('id' => 132, 'alpha2' => 'cv', 'alpha3' => 'cpv', 'name' => 'الرأس الأخضر'),
//             array('id' => 136, 'alpha2' => 'ky', 'alpha3' => 'cym', 'name' => 'جزر كايمان'),
//             array('id' => 140, 'alpha2' => 'cf', 'alpha3' => 'caf', 'name' => 'جمهورية أفريقيا الوسطى'),
//             array('id' => 148, 'alpha2' => 'td', 'alpha3' => 'tcd', 'name' => 'تشاد'),
//             array('id' => 152, 'alpha2' => 'cl', 'alpha3' => 'chl', 'name' => 'تشيلي'),
//             array('id' => 156, 'alpha2' => 'cn', 'alpha3' => 'chn', 'name' => 'الصين'),
//             array('id' => 162, 'alpha2' => 'cx', 'alpha3' => 'cxr', 'name' => 'جزيرة كريسماس'),
//             array('id' => 166, 'alpha2' => 'cc', 'alpha3' => 'cck', 'name' => 'جزر كوكوس'),
//             array('id' => 170, 'alpha2' => 'co', 'alpha3' => 'col', 'name' => 'كولومبيا'),
//             array('id' => 174, 'alpha2' => 'km', 'alpha3' => 'com', 'name' => 'جزر القمر'),
//             array('id' => 178, 'alpha2' => 'cg', 'alpha3' => 'cog', 'name' => 'جمهورية الكونغو'),
//             array('id' => 180, 'alpha2' => 'cd', 'alpha3' => 'cod', 'name' => 'جمهورية الكونغو الديمقراطية'),
//             array('id' => 184, 'alpha2' => 'ck', 'alpha3' => 'cok', 'name' => 'جزر كوك'),
//             array('id' => 188, 'alpha2' => 'cr', 'alpha3' => 'cri', 'name' => 'كوستاريكا'),
//             array('id' => 384, 'alpha2' => 'ci', 'alpha3' => 'civ', 'name' => 'ساحل العاج'),
//             array('id' => 191, 'alpha2' => 'hr', 'alpha3' => 'hrv', 'name' => 'كرواتيا'),
//             array('id' => 192, 'alpha2' => 'cu', 'alpha3' => 'cub', 'name' => 'كوبا'),
//             array('id' => 531, 'alpha2' => 'cw', 'alpha3' => 'cuw', 'name' => 'كوراساو'),
//             array('id' => 196, 'alpha2' => 'cy', 'alpha3' => 'cyp', 'name' => 'قبرص'),
//             array('id' => 203, 'alpha2' => 'cz', 'alpha3' => 'cze', 'name' => 'جمهورية التشيك'),
//             array('id' => 208, 'alpha2' => 'dk', 'alpha3' => 'dnk', 'name' => 'الدنمارك'),
//             array('id' => 262, 'alpha2' => 'dj', 'alpha3' => 'dji', 'name' => 'جيبوتي'),
//             array('id' => 212, 'alpha2' => 'dm', 'alpha3' => 'dma', 'name' => 'دومينيكا'),
//             array('id' => 214, 'alpha2' => 'do', 'alpha3' => 'dom', 'name' => 'جمهورية الدومينيكان'),
//             array('id' => 218, 'alpha2' => 'ec', 'alpha3' => 'ecu', 'name' => 'الإكوادور'),
//             array('id' => 818, 'alpha2' => 'eg', 'alpha3' => 'egy', 'name' => 'مصر'),
//             array('id' => 222, 'alpha2' => 'sv', 'alpha3' => 'slv', 'name' => 'السلفادور'),
//             array('id' => 226, 'alpha2' => 'gq', 'alpha3' => 'gnq', 'name' => 'غينيا الاستوائية'),
//             array('id' => 232, 'alpha2' => 'er', 'alpha3' => 'eri', 'name' => 'إريتريا'),
//             array('id' => 233, 'alpha2' => 'ee', 'alpha3' => 'est', 'name' => 'إستونيا'),
//             array('id' => 231, 'alpha2' => 'et', 'alpha3' => 'eth', 'name' => 'إثيوبيا'),
//             array('id' => 238, 'alpha2' => 'fk', 'alpha3' => 'flk', 'name' => 'جزر فوكلاند'),
//             array('id' => 234, 'alpha2' => 'fo', 'alpha3' => 'fro', 'name' => 'جزر فارو'),
//             array('id' => 242, 'alpha2' => 'fj', 'alpha3' => 'fji', 'name' => 'فيجي'),
//             array('id' => 246, 'alpha2' => 'fi', 'alpha3' => 'fin', 'name' => 'فنلندا'),
//             array('id' => 250, 'alpha2' => 'fr', 'alpha3' => 'fra', 'name' => 'فرنسا'),
//             array('id' => 254, 'alpha2' => 'gf', 'alpha3' => 'guf', 'name' => 'غويانا الفرنسية'),
//             array('id' => 258, 'alpha2' => 'pf', 'alpha3' => 'pyf', 'name' => 'بولينزيا الفرنسية'),
//             array('id' => 260, 'alpha2' => 'tf', 'alpha3' => 'atf', 'name' => 'أراض فرنسية جنوبية وأنتارتيكية'),
//             array('id' => 266, 'alpha2' => 'ga', 'alpha3' => 'gab', 'name' => 'الغابون'),
//             array('id' => 270, 'alpha2' => 'gm', 'alpha3' => 'gmb', 'name' => 'غامبيا'),
//             array('id' => 268, 'alpha2' => 'ge', 'alpha3' => 'geo', 'name' => 'جورجيا'),
//             array('id' => 276, 'alpha2' => 'de', 'alpha3' => 'deu', 'name' => 'ألمانيا'),
//             array('id' => 288, 'alpha2' => 'gh', 'alpha3' => 'gha', 'name' => 'غانا'),
//             array('id' => 292, 'alpha2' => 'gi', 'alpha3' => 'gib', 'name' => 'جبل طارق'),
//             array('id' => 300, 'alpha2' => 'gr', 'alpha3' => 'grc', 'name' => 'اليونان'),
//             array('id' => 304, 'alpha2' => 'gl', 'alpha3' => 'grl', 'name' => 'جرينلاند'),
//             array('id' => 308, 'alpha2' => 'gd', 'alpha3' => 'grd', 'name' => 'غرينادا'),
//             array('id' => 312, 'alpha2' => 'gp', 'alpha3' => 'glp', 'name' => 'غوادلوب'),
//             array('id' => 316, 'alpha2' => 'gu', 'alpha3' => 'gum', 'name' => 'غوام'),
//             array('id' => 320, 'alpha2' => 'gt', 'alpha3' => 'gtm', 'name' => 'غواتيمالا'),
//             array('id' => 831, 'alpha2' => 'gg', 'alpha3' => 'ggy', 'name' => 'غيرنزي'),
//             array('id' => 324, 'alpha2' => 'gn', 'alpha3' => 'gin', 'name' => 'غينيا'),
//             array('id' => 624, 'alpha2' => 'gw', 'alpha3' => 'gnb', 'name' => 'غينيا بيساو'),
//             array('id' => 328, 'alpha2' => 'gy', 'alpha3' => 'guy', 'name' => 'غيانا'),
//             array('id' => 332, 'alpha2' => 'ht', 'alpha3' => 'hti', 'name' => 'هايتي'),
//             array('id' => 334, 'alpha2' => 'hm', 'alpha3' => 'hmd', 'name' => 'جزيرة هيرد وجزر ماكدونالد'),
//             array('id' => 336, 'alpha2' => 'va', 'alpha3' => 'vat', 'name' => 'الفاتيكان'),
//             array('id' => 340, 'alpha2' => 'hn', 'alpha3' => 'hnd', 'name' => 'هندوراس'),
//             array('id' => 344, 'alpha2' => 'hk', 'alpha3' => 'hkg', 'name' => 'هونغ كونغ'),
//             array('id' => 348, 'alpha2' => 'hu', 'alpha3' => 'hun', 'name' => 'المجر'),
//             array('id' => 352, 'alpha2' => 'is', 'alpha3' => 'isl', 'name' => 'آيسلندا'),
//             array('id' => 356, 'alpha2' => 'in', 'alpha3' => 'ind', 'name' => 'الهند'),
//             array('id' => 360, 'alpha2' => 'id', 'alpha3' => 'idn', 'name' => 'إندونيسيا'),
//             array('id' => 364, 'alpha2' => 'ir', 'alpha3' => 'irn', 'name' => 'إيران'),
//             array('id' => 368, 'alpha2' => 'iq', 'alpha3' => 'irq', 'name' => 'العراق'),
//             array('id' => 372, 'alpha2' => 'ie', 'alpha3' => 'irl', 'name' => 'أيرلندا'),
//             array('id' => 833, 'alpha2' => 'im', 'alpha3' => 'imn', 'name' => 'جزيرة مان'),
////             array('id' => 376, 'alpha2' => 'il', 'alpha3' => 'isr', 'name' => 'إسرائيل'),
//             array('id' => 380, 'alpha2' => 'it', 'alpha3' => 'ita', 'name' => 'إيطاليا'),
//             array('id' => 388, 'alpha2' => 'jm', 'alpha3' => 'jam', 'name' => 'جامايكا'),
//             array('id' => 392, 'alpha2' => 'jp', 'alpha3' => 'jpn', 'name' => 'اليابان'),
//             array('id' => 832, 'alpha2' => 'je', 'alpha3' => 'jey', 'name' => 'جيرزي'),
//             array('id' => 400, 'alpha2' => 'jo', 'alpha3' => 'jor', 'name' => 'الأردن'),
//             array('id' => 398, 'alpha2' => 'kz', 'alpha3' => 'kaz', 'name' => 'كازاخستان'),
//             array('id' => 404, 'alpha2' => 'ke', 'alpha3' => 'ken', 'name' => 'كينيا'),
//             array('id' => 296, 'alpha2' => 'ki', 'alpha3' => 'kir', 'name' => 'كيريباتي'),
//             array('id' => 408, 'alpha2' => 'kp', 'alpha3' => 'prk', 'name' => 'كوريا الشمالية'),
//             array('id' => 410, 'alpha2' => 'kr', 'alpha3' => 'kor', 'name' => 'كوريا الجنوبية'),
//             array('id' => 414, 'alpha2' => 'kw', 'alpha3' => 'kwt', 'name' => 'الكويت'),
//             array('id' => 417, 'alpha2' => 'kg', 'alpha3' => 'kgz', 'name' => 'قيرغيزستان'),
//             array('id' => 418, 'alpha2' => 'la', 'alpha3' => 'lao', 'name' => 'لاوس'),
//             array('id' => 428, 'alpha2' => 'lv', 'alpha3' => 'lva', 'name' => 'لاتفيا'),
//             array('id' => 422, 'alpha2' => 'lb', 'alpha3' => 'lbn', 'name' => 'لبنان'),
//             array('id' => 426, 'alpha2' => 'ls', 'alpha3' => 'lso', 'name' => 'ليسوتو'),
//             array('id' => 430, 'alpha2' => 'lr', 'alpha3' => 'lbr', 'name' => 'ليبيريا'),
//             array('id' => 434, 'alpha2' => 'ly', 'alpha3' => 'lby', 'name' => 'ليبيا'),
//             array('id' => 438, 'alpha2' => 'li', 'alpha3' => 'lie', 'name' => 'ليختنشتاين'),
//             array('id' => 440, 'alpha2' => 'lt', 'alpha3' => 'ltu', 'name' => 'ليتوانيا'),
//             array('id' => 442, 'alpha2' => 'lu', 'alpha3' => 'lux', 'name' => 'لوكسمبورغ'),
//             array('id' => 446, 'alpha2' => 'mo', 'alpha3' => 'mac', 'name' => 'ماكاو'),
//             array('id' => 807, 'alpha2' => 'mk', 'alpha3' => 'mkd', 'name' => 'مقدونيا'),
//             array('id' => 450, 'alpha2' => 'mg', 'alpha3' => 'mdg', 'name' => 'مدغشقر'),
//             array('id' => 454, 'alpha2' => 'mw', 'alpha3' => 'mwi', 'name' => 'مالاوي'),
//             array('id' => 458, 'alpha2' => 'my', 'alpha3' => 'mys', 'name' => 'ماليزيا'),
//             array('id' => 462, 'alpha2' => 'mv', 'alpha3' => 'mdv', 'name' => 'جزر المالديف'),
//             array('id' => 466, 'alpha2' => 'ml', 'alpha3' => 'mli', 'name' => 'مالي'),
//             array('id' => 470, 'alpha2' => 'mt', 'alpha3' => 'mlt', 'name' => 'مالطا'),
//             array('id' => 584, 'alpha2' => 'mh', 'alpha3' => 'mhl', 'name' => 'جزر مارشال'),
//             array('id' => 474, 'alpha2' => 'mq', 'alpha3' => 'mtq', 'name' => 'مارتينيك'),
//             array('id' => 478, 'alpha2' => 'mr', 'alpha3' => 'mrt', 'name' => 'موريتانيا'),
//             array('id' => 480, 'alpha2' => 'mu', 'alpha3' => 'mus', 'name' => 'موريشيوس'),
//             array('id' => 175, 'alpha2' => 'yt', 'alpha3' => 'myt', 'name' => 'مايوت'),
//             array('id' => 484, 'alpha2' => 'mx', 'alpha3' => 'mex', 'name' => 'المكسيك'),
//             array('id' => 583, 'alpha2' => 'fm', 'alpha3' => 'fsm', 'name' => 'ولايات ميكرونيسيا المتحدة'),
//             array('id' => 504, 'alpha2' => 'ma', 'alpha3' => 'mar', 'name' => 'المغرب'),
//             array('id' => 498, 'alpha2' => 'md', 'alpha3' => 'mda', 'name' => 'مولدوفا'),
//             array('id' => 492, 'alpha2' => 'mc', 'alpha3' => 'mco', 'name' => 'موناكو'),
//             array('id' => 496, 'alpha2' => 'mn', 'alpha3' => 'mng', 'name' => 'منغوليا'),
//             array('id' => 499, 'alpha2' => 'me', 'alpha3' => 'mne', 'name' => 'الجبل الأسود'),
//             array('id' => 500, 'alpha2' => 'ms', 'alpha3' => 'msr', 'name' => 'مونتسرات'),
//             array('id' => 508, 'alpha2' => 'mz', 'alpha3' => 'moz', 'name' => 'موزمبيق'),
//             array('id' => 104, 'alpha2' => 'mm', 'alpha3' => 'mmr', 'name' => 'ميانمار'),
//             array('id' => 516, 'alpha2' => 'na', 'alpha3' => 'nam', 'name' => 'ناميبيا'),
//             array('id' => 520, 'alpha2' => 'nr', 'alpha3' => 'nru', 'name' => 'ناورو'),
//             array('id' => 524, 'alpha2' => 'np', 'alpha3' => 'npl', 'name' => 'نيبال'),
//             array('id' => 528, 'alpha2' => 'nl', 'alpha3' => 'nld', 'name' => 'هولندا'),
//             array('id' => 540, 'alpha2' => 'nc', 'alpha3' => 'ncl', 'name' => 'كاليدونيا الجديدة'),
//             array('id' => 554, 'alpha2' => 'nz', 'alpha3' => 'nzl', 'name' => 'نيوزيلندا'),
//             array('id' => 558, 'alpha2' => 'ni', 'alpha3' => 'nic', 'name' => 'نيكاراغوا'),
//             array('id' => 562, 'alpha2' => 'ne', 'alpha3' => 'ner', 'name' => 'النيجر'),
//             array('id' => 566, 'alpha2' => 'ng', 'alpha3' => 'nga', 'name' => 'نيجيريا'),
//             array('id' => 570, 'alpha2' => 'nu', 'alpha3' => 'niu', 'name' => 'نييوي'),
//             array('id' => 574, 'alpha2' => 'nf', 'alpha3' => 'nfk', 'name' => 'جزيرة نورفولك'),
//             array('id' => 580, 'alpha2' => 'mp', 'alpha3' => 'mnp', 'name' => 'جزر ماريانا الشمالية'),
//             array('id' => 578, 'alpha2' => 'no', 'alpha3' => 'nor', 'name' => 'النرويج'),
//             array('id' => 512, 'alpha2' => 'om', 'alpha3' => 'omn', 'name' => 'عمان'),
//             array('id' => 586, 'alpha2' => 'pk', 'alpha3' => 'pak', 'name' => 'باكستان'),
//             array('id' => 585, 'alpha2' => 'pw', 'alpha3' => 'plw', 'name' => 'بالاو'),
//             array('id' => 275, 'alpha2' => 'ps', 'alpha3' => 'pse', 'name' => 'فلسطين'),
//             array('id' => 591, 'alpha2' => 'pa', 'alpha3' => 'pan', 'name' => 'بنما'),
//             array('id' => 598, 'alpha2' => 'pg', 'alpha3' => 'png', 'name' => 'بابوا غينيا الجديدة'),
//             array('id' => 600, 'alpha2' => 'py', 'alpha3' => 'pry', 'name' => 'باراغواي'),
//             array('id' => 604, 'alpha2' => 'pe', 'alpha3' => 'per', 'name' => 'بيرو'),
//             array('id' => 608, 'alpha2' => 'ph', 'alpha3' => 'phl', 'name' => 'الفلبين'),
//             array('id' => 612, 'alpha2' => 'pn', 'alpha3' => 'pcn', 'name' => 'جزر بيتكيرن'),
//             array('id' => 616, 'alpha2' => 'pl', 'alpha3' => 'pol', 'name' => 'بولندا'),
//             array('id' => 620, 'alpha2' => 'pt', 'alpha3' => 'prt', 'name' => 'البرتغال'),
//             array('id' => 630, 'alpha2' => 'pr', 'alpha3' => 'pri', 'name' => 'بورتوريكو'),
//             array('id' => 634, 'alpha2' => 'qa', 'alpha3' => 'qat', 'name' => 'قطر'),
//             array('id' => 638, 'alpha2' => 're', 'alpha3' => 'reu', 'name' => 'Réunion'),
//             array('id' => 642, 'alpha2' => 'ro', 'alpha3' => 'rou', 'name' => 'رومانيا'),
//             array('id' => 643, 'alpha2' => 'ru', 'alpha3' => 'rus', 'name' => 'روسيا'),
//             array('id' => 646, 'alpha2' => 'rw', 'alpha3' => 'rwa', 'name' => 'رواندا'),
//             array('id' => 652, 'alpha2' => 'bl', 'alpha3' => 'blm', 'name' => 'سان بارتيلمي'),
//             array('id' => 654, 'alpha2' => 'sh', 'alpha3' => 'shn', 'name' => 'سانت هيلانة وأسينشين وتريستان دا كونا'),
//             array('id' => 659, 'alpha2' => 'kn', 'alpha3' => 'kna', 'name' => 'سانت كيتس ونيفيس'),
//             array('id' => 662, 'alpha2' => 'lc', 'alpha3' => 'lca', 'name' => 'سانت لوسيا'),
//             array('id' => 663, 'alpha2' => 'mf', 'alpha3' => 'maf', 'name' => 'تجمع سان مارتين'),
//             array('id' => 666, 'alpha2' => 'pm', 'alpha3' => 'spm', 'name' => 'سان بيير وميكلون'),
//             array('id' => 670, 'alpha2' => 'vc', 'alpha3' => 'vct', 'name' => 'سانت فينسنت والغرينادين'),
//             array('id' => 882, 'alpha2' => 'ws', 'alpha3' => 'wsm', 'name' => 'ساموا'),
//             array('id' => 674, 'alpha2' => 'sm', 'alpha3' => 'smr', 'name' => 'سان مارينو'),
//             array('id' => 678, 'alpha2' => 'st', 'alpha3' => 'stp', 'name' => 'ساو تومي وبرينسيب'),
//             array('id' => 682, 'alpha2' => 'sa', 'alpha3' => 'sau', 'name' => 'السعودية'),
//             array('id' => 686, 'alpha2' => 'sn', 'alpha3' => 'sen', 'name' => 'السنغال'),
//             array('id' => 688, 'alpha2' => 'rs', 'alpha3' => 'srb', 'name' => 'صربيا'),
//             array('id' => 690, 'alpha2' => 'sc', 'alpha3' => 'syc', 'name' => 'سيشل'),
//             array('id' => 694, 'alpha2' => 'sl', 'alpha3' => 'sle', 'name' => 'سيراليون'),
//             array('id' => 702, 'alpha2' => 'sg', 'alpha3' => 'sgp', 'name' => 'سنغافورة'),
//             array('id' => 534, 'alpha2' => 'sx', 'alpha3' => 'sxm', 'name' => 'سينت مارتن'),
//             array('id' => 703, 'alpha2' => 'sk', 'alpha3' => 'svk', 'name' => 'سلوفاكيا'),
//             array('id' => 705, 'alpha2' => 'si', 'alpha3' => 'svn', 'name' => 'سلوفينيا'),
//             array('id' => 90 , 'alpha2' => 'sb', 'alpha3' => 'slb', 'name' => 'جزر سليمان'),
//             array('id' => 706, 'alpha2' => 'so', 'alpha3' => 'som', 'name' => 'الصومال'),
//             array('id' => 710, 'alpha2' => 'za', 'alpha3' => 'zaf', 'name' => 'جنوب إفريقيا'),
//             array('id' => 239, 'alpha2' => 'gs', 'alpha3' => 'sgs', 'name' => 'جورجيا الجنوبية وجزر ساندويتش الجنوبية'),
//             array('id' => 728, 'alpha2' => 'ss', 'alpha3' => 'ssd', 'name' => 'جنوب السودان'),
//             array('id' => 724, 'alpha2' => 'es', 'alpha3' => 'esp', 'name' => 'إسبانيا'),
//             array('id' => 144, 'alpha2' => 'lk', 'alpha3' => 'lka', 'name' => 'سريلانكا'),
//             array('id' => 729, 'alpha2' => 'sd', 'alpha3' => 'sdn', 'name' => 'السودان'),
//             array('id' => 740, 'alpha2' => 'sr', 'alpha3' => 'sur', 'name' => 'سورينام'),
//             array('id' => 744, 'alpha2' => 'sj', 'alpha3' => 'sjm', 'name' => 'سفالبارد ويان ماين'),
//             array('id' => 748, 'alpha2' => 'sz', 'alpha3' => 'swz', 'name' => 'إسواتيني'),
//             array('id' => 752, 'alpha2' => 'se', 'alpha3' => 'swe', 'name' => 'السويد'),
//             array('id' => 756, 'alpha2' => 'ch', 'alpha3' => 'che', 'name' => 'سويسرا'),
//             array('id' => 760, 'alpha2' => 'sy', 'alpha3' => 'syr', 'name' => 'سوريا'),
//             array('id' => 158, 'alpha2' => 'tw', 'alpha3' => 'twn', 'name' => 'تايوان'),
//             array('id' => 762, 'alpha2' => 'tj', 'alpha3' => 'tjk', 'name' => 'طاجيكستان'),
//             array('id' => 834, 'alpha2' => 'tz', 'alpha3' => 'tza', 'name' => 'تنزانيا'),
//             array('id' => 764, 'alpha2' => 'th', 'alpha3' => 'tha', 'name' => 'تايلاند'),
//             array('id' => 626, 'alpha2' => 'tl', 'alpha3' => 'tls', 'name' => 'تيمور الشرقية'),
//             array('id' => 768, 'alpha2' => 'tg', 'alpha3' => 'tgo', 'name' => 'توغو'),
//             array('id' => 772, 'alpha2' => 'tk', 'alpha3' => 'tkl', 'name' => 'توكيلاو'),
//             array('id' => 776, 'alpha2' => 'to', 'alpha3' => 'ton', 'name' => 'تونغا'),
//             array('id' => 780, 'alpha2' => 'tt', 'alpha3' => 'tto', 'name' => 'ترينيداد وتوباغو'),
//             array('id' => 788, 'alpha2' => 'tn', 'alpha3' => 'tun', 'name' => 'تونس'),
//             array('id' => 792, 'alpha2' => 'tr', 'alpha3' => 'tur', 'name' => 'تركيا'),
//             array('id' => 795, 'alpha2' => 'tm', 'alpha3' => 'tkm', 'name' => 'تركمانستان'),
//             array('id' => 796, 'alpha2' => 'tc', 'alpha3' => 'tca', 'name' => 'جزر توركس وكايكوس'),
//             array('id' => 798, 'alpha2' => 'tv', 'alpha3' => 'tuv', 'name' => 'توفالو'),
//             array('id' => 800, 'alpha2' => 'ug', 'alpha3' => 'uga', 'name' => 'أوغندا'),
//             array('id' => 804, 'alpha2' => 'ua', 'alpha3' => 'ukr', 'name' => 'أوكرانيا'),
//             array('id' => 784, 'alpha2' => 'ae', 'alpha3' => 'are', 'name' => 'الإمارات العربية المتحدة'),
//             array('id' => 826, 'alpha2' => 'gb', 'alpha3' => 'gbr', 'name' => 'المملكة المتحدة'),
//             array('id' => 840, 'alpha2' => 'us', 'alpha3' => 'usa', 'name' => 'الولايات المتحدة'),
//             array('id' => 581, 'alpha2' => 'um', 'alpha3' => 'umi', 'name' => 'جزر الولايات المتحدة الصغيرة النائية'),
//             array('id' => 858, 'alpha2' => 'uy', 'alpha3' => 'ury', 'name' => 'الأوروغواي'),
//             array('id' => 860, 'alpha2' => 'uz', 'alpha3' => 'uzb', 'name' => 'أوزبكستان'),
//             array('id' => 548, 'alpha2' => 'vu', 'alpha3' => 'vut', 'name' => 'فانواتو'),
//             array('id' => 862, 'alpha2' => 've', 'alpha3' => 'ven', 'name' => 'فنزويلا'),
//             array('id' => 704, 'alpha2' => 'vn', 'alpha3' => 'vnm', 'name' => 'فيتنام'),
//             array('id' => 92 , 'alpha2' => 'vg', 'alpha3' => 'vgb', 'name' => 'جزر العذراء البريطانية'),
//             array('id' => 850, 'alpha2' => 'vi', 'alpha3' => 'vir', 'name' => 'جزر العذراء الأمريكية'),
//             array('id' => 876, 'alpha2' => 'wf', 'alpha3' => 'wlf', 'name' => 'واليس وفوتونا'),
//             array('id' => 732, 'alpha2' => 'eh', 'alpha3' => 'esh', 'name' => 'الصحراء الغربية'),
//             array('id' => 887, 'alpha2' => 'ye', 'alpha3' => 'yem', 'name' => 'اليمن'),
//             array('id' => 894, 'alpha2' => 'zm', 'alpha3' => 'zmb', 'name' => 'زامبيا'),
//             array('id' => 716, 'alpha2' => 'zw', 'alpha3' => 'zwe', 'name' => 'زيمبابوي'),
//        );
//
//         foreach ( $countries_ar  as $country ){
//             Country::create([
//                 'alpha2'  => $country['alpha2'],
//                 'alpha3'  => $country['alpha3'],
//                 'ar' => [
//                     'name' => $country['name']
//                 ],
//                 'en' => [
//                     'name' => 'Saudi Arabia'
//                 ]
//             ]);
//        }
//
//         return sizeof( $countries_ar );
//
//    }
}

